// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package grpcserver

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	SourceConfigMtlsCaCertPath     = "mtls.ca.certPath"
	SourceConfigMtlsDisabled       = "mtls.disabled"
	SourceConfigMtlsServerCertPath = "mtls.server.certPath"
	SourceConfigMtlsServerKeyPath  = "mtls.server.keyPath"
	SourceConfigUrl                = "url"
)

func (SourceConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		SourceConfigMtlsCaCertPath: {
			Default:     "",
			Description: "the root CA certificate path.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		SourceConfigMtlsDisabled: {
			Default:     "false",
			Description: "option to disable mTLS secure connection, set it to `true` for an insecure connection.",
			Type:        config.ParameterTypeBool,
			Validations: []config.Validation{},
		},
		SourceConfigMtlsServerCertPath: {
			Default:     "",
			Description: "the server certificate path.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		SourceConfigMtlsServerKeyPath: {
			Default:     "",
			Description: "the server private key path.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		SourceConfigUrl: {
			Default:     "",
			Description: "url to gRPC server",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
